name: Stardust

on:
  schedule:
    - cron: "0 9 * * 0" # At 09:00 on Sunday

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: micnncim/action-stardust@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: micnncim
          interval: 168h
          slack_enabled: true
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: github-star
