name: Stardust

on:
  schedule:
    - cron: "0 13 * * 1" # At 13:00 on Monday

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: micnncim/action-stardust@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: micnncim
          interval: 168h # 1 week
          slack_enabled: true
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: github-star
